---
- name: Setting up k8's
  hosts: jenkins-slave
  become: true
  vars:
    eks_cluster_name: "{{ cluster_name }}"  # Map cluster_name to eks_cluster_name

  tasks:

    # Downloading kuberntes binary
    - name: Download kubectl binary
      get_url:
        url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.9/2023-01-11/bin/linux/amd64/kubectl
        dest: /tmp/kubectl
        mode: '0755'

    # Check if kubectl binary exists
    - name: Check if kubectl binary exists
      stat:
        path: /tmp/kubectl
      register: kubectl_file

    # Making kubectl executable
    - name: Make kubectl executable
      file:
        path: /tmp/kubectl
        mode: '0755'
        state: file
      when: kubectl_file.stat.exists

    # Moving kubectl
    - name: Move kubectl to /usr/local/bin
      command: mv /tmp/kubectl /usr/local/bin/kubectl
      when: kubectl_file.stat.exists

    # Update kubeconfig for AWS EKS cluster (dynamic name)
    - name: Update kubeconfig for AWS EKS cluster
      command: aws eks update-kubeconfig --region us-east-1 --name {{ eks_cluster_name }}
      register: kubeconfig_output
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    # Display kubeconfig update result
    - name: Display kubeconfig update output
      debug:
        msg: "{{ kubeconfig_output.stdout }}"

    # Checking kubectl version
    - name: Check kubectl version
      command: kubectl version --client
      register: kubectl_version_output
      environment:
        PATH: "{{ansible_env.PATH }}:/usr/local/bin"


    # Displaying the version of Kubectl
    - name: Displaying the version
      debug:
        msg: "{{kubectl_version_output.stdout}}"
